# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/User/Desktop/SSC/Proiect/Proiect1/Proiect1.cache/wt [current_project]
set_property parent.project_path C:/Users/User/Desktop/SSC/Proiect/Proiect1/Proiect1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/User/Desktop/SSC/Proiect/Proiect1/Proiect1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/User/Desktop/SSC/Proiect/Proiect1/Proiect1.srcs/sources_1/new/CarryAdder.vhd
  C:/Users/User/Desktop/SSC/Proiect/Proiect1/Proiect1.srcs/sources_1/imports/src/multiplicator.vhd
  C:/Users/User/Desktop/SSC/Proiect/Proiect1/Proiect1.srcs/sources_1/imports/src/BCDAdder.vhd
  C:/Users/User/Desktop/SSC/Proiect/Proiect1/Proiect1.srcs/sources_1/new/Freq_Div.vhd
  C:/Users/User/Desktop/SSC/Proiect/Proiect1/Proiect1.srcs/sources_1/imports/src/dmux_2to1_2bits.vhd
  C:/Users/User/Desktop/SSC/Proiect/Proiect1/Proiect1.srcs/sources_1/imports/src/CounterModulo_5.vhd
  C:/Users/User/Desktop/SSC/Proiect/Proiect1/Proiect1.srcs/sources_1/imports/src/CounterModulo_4.vhd
  C:/Users/User/Desktop/SSC/Proiect/Proiect1/Proiect1.srcs/sources_1/imports/src/CounterModulo_10.vhd
  C:/Users/User/Desktop/SSC/Proiect/Proiect1/Proiect1.srcs/sources_1/imports/src/BCDtoBinary.vhd
  C:/Users/User/Desktop/SSC/Proiect/Proiect1/Proiect1.srcs/sources_1/imports/src/IEEE_Multiplication.vhd
  C:/Users/User/Desktop/SSC/Proiect/Proiect1/Proiect1.srcs/sources_1/imports/src/segment7.vhd
  C:/Users/User/Desktop/SSC/Proiect/Proiect1/Proiect1.srcs/sources_1/imports/src/NumberRegister.vhd
  C:/Users/User/Desktop/SSC/Proiect/Proiect1/Proiect1.srcs/sources_1/new/Main.vhd
  C:/Users/User/Desktop/SSC/Proiect/Proiect1/Proiect1.srcs/sources_1/imports/src/IEEEtoBCD.vhd
  C:/Users/User/Desktop/SSC/Proiect/Proiect1/Proiect1.srcs/sources_1/imports/src/Debouncer.vhd
  C:/Users/User/Desktop/SSC/Proiect/Proiect1/Proiect1.srcs/sources_1/imports/src/BCDtoIEEE.vhd
  C:/Users/User/Desktop/SSC/Proiect/Proiect1/Proiect1.srcs/sources_1/imports/src/control.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/User/Desktop/SSC/Proiect/Proiect1/Proiect1.srcs/constrs_1/imports/src/Basys-3-Master.xdc
set_property used_in_implementation false [get_files C:/Users/User/Desktop/SSC/Proiect/Proiect1/Proiect1.srcs/constrs_1/imports/src/Basys-3-Master.xdc]


synth_design -top Control -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Control.dcp

catch { report_utilization -file Control_utilization_synth.rpt -pb Control_utilization_synth.pb }
